export const skills=[
    'HTML',
    'CSS',
    'JavaScript',
     'DOM',
    'React',
    'ReduxToolkit',
    'Next Js',
    'TailwindCSS',
    'BootStrap',
    'UI/UX Designing',
     'TypeScript',
     'NodeJS',
     'Express',
     'REST APIs',
    'Java',
    'C',
    'MySQL',
    'MongoDB',
    'Git',
    'Github',

]